const comunas = [
  { label: "Arica", value: "Arica" },
  { label: "Camarones", value: "Camarones" },
  { label: "General Lagos", value: "General Lagos" },
  { label: "Putre", value: "Putre" },
  { label: "Alto Hospicio", value: "Alto Hospicio" },
  { label: "Iquique", value: "Iquique" },
  { label: "Camiña", value: "Camiña" },
  { label: "Colchane", value: "Colchane" },
  { label: "Huara", value: "Huara" },
  { label: "Pica", value: "Pica" },
  { label: "Pozo Almonte", value: "Pozo Almonte" },
  { label: "Antofagasta", value: "Antofagasta" },
  { label: "Mejillones", value: "Mejillones" },
  { label: "Sierra Gorda", value: "Sierra Gorda" },
  { label: "Taltal", value: "Taltal" },
  { label: "Calama", value: "Calama" },
  { label: "Ollague", value: "Ollague" },
  { label: "San Pedro de Atacama", value: "San Pedro de Atacama" },
  { label: "María Elena", value: "María Elena" },
  { label: "Tocopilla", value: "Tocopilla" },
  { label: "Chañaral", value: "Chañaral" },
  { label: "Diego de Almagro", value: "Diego de Almagro" },
  { label: "Caldera", value: "Caldera" },
  { label: "Copiapó", value: "Copiapó" },
  { label: "Tierra Amarilla", value: "Tierra Amarilla" },
  { label: "Alto del Carmen", value: "Alto del Carmen" },
  { label: "Freirina", value: "Freirina" },
  { label: "Huasco", value: "Huasco" },
  { label: "Vallenar", value: "Vallenar" },
  { label: "Canela", value: "Canela" },
  { label: "Illapel", value: "Illapel" },
  { label: "Los Vilos", value: "Los Vilos" },
  { label: "Salamanca", value: "Salamanca" },
  { label: "Andacollo", value: "Andacollo" },
  { label: "Coquimbo", value: "Coquimbo" },
  { label: "La Higuera", value: "La Higuera" },
  { label: "La Serena", value: "La Serena" },
  { label: "Paihuaco", value: "Paihuaco" },
  { label: "Vicuña", value: "Vicuña" },
  { label: "Combarbalá", value: "Combarbalá" },
  { label: "Monte Patria", value: "Monte Patria" },
  { label: "Ovalle", value: "Ovalle" },
  { label: "Punitaqui", value: "Punitaqui" },
  { label: "Río Hurtado", value: "Río Hurtado" },
  { label: "Isla de Pascua", value: "Isla de Pascua" },
  { label: "Calle Larga", value: "Calle Larga" },
  { label: "Los Andes", value: "Los Andes" },
  { label: "Rinconada", value: "Rinconada" },
  { label: "San Esteban", value: "San Esteban" },
  { label: "La Ligua", value: "La Ligua" },
  { label: "Papudo", value: "Papudo" },
  { label: "Petorca", value: "Petorca" },
  { label: "Zapallar", value: "Zapallar" },
  { label: "Hijuelas", value: "Hijuelas" },
  { label: "La Calera", value: "La Calera" },
  { label: "La Cruz", value: "La Cruz" },
  { label: "Limache", value: "Limache" },
  { label: "Nogales", value: "Nogales" },
  { label: "Olmué", value: "Olmué" },
  { label: "Quillota", value: "Quillota" },
  { label: "Algarrobo", value: "Algarrobo" },
  { label: "Cartagena", value: "Cartagena" },
  { label: "El Quisco", value: "El Quisco" },
  { label: "El Tabo", value: "El Tabo" },
  { label: "San Antonio", value: "San Antonio" },
  { label: "Santo Domingo", value: "Santo Domingo" },
  { label: "Catemu", value: "Catemu" },
  { label: "Llaillay", value: "Llaillay" },
  { label: "Panquehue", value: "Panquehue" },
  { label: "Putaendo", value: "Putaendo" },
  { label: "San Felipe", value: "San Felipe" },
  { label: "Santa María", value: "Santa María" },
  { label: "Casablanca", value: "Casablanca" },
  { label: "Concón", value: "Concón" },
  { label: "Juan Fernández", value: "Juan Fernández" },
  { label: "Puchuncaví", value: "Puchuncaví" },
  { label: "Quilpué", value: "Quilpué" },
  { label: "Quintero", value: "Quintero" },
  { label: "Valparaíso", value: "Valparaíso" },
  { label: "Villa Alemana", value: "Villa Alemana" },
  { label: "Viña del Mar", value: "Viña del Mar" },
  { label: "Colina", value: "Colina" },
  { label: "Lampa", value: "Lampa" },
  { label: "Tiltil", value: "Tiltil" },
  { label: "Pirque", value: "Pirque" },
  { label: "Puente Alto", value: "Puente Alto" },
  { label: "San José de Maipo", value: "San José de Maipo" },
  { label: "Buin", value: "Buin" },
  { label: "Calera de Tango", value: "Calera de Tango" },
  { label: "Paine", value: "Paine" },
  { label: "San Bernardo", value: "San Bernardo" },
  { label: "Alhué", value: "Alhué" },
  { label: "Curacaví", value: "Curacaví" },
  { label: "María Pinto", value: "María Pinto" },
  { label: "Melipilla", value: "Melipilla" },
  { label: "San Pedro", value: "San Pedro" },
  { label: "Cerrillos", value: "Cerrillos" },
  { label: "Cerro Navia", value: "Cerro Navia" },
  { label: "Conchalí", value: "Conchalí" },
  { label: "El Bosque", value: "El Bosque" },
  { label: "Estación Central", value: "Estación Central" },
  { label: "Huechuraba", value: "Huechuraba" },
  { label: "Independencia", value: "Independencia" },
  { label: "La Cisterna", value: "La Cisterna" },
  { label: "La Granja", value: "La Granja" },
  { label: "La Florida", value: "La Florida" },
  { label: "La Pintana", value: "La Pintana" },
  { label: "La Reina", value: "La Reina" },
  { label: "Las Condes", value: "Las Condes" },
  { label: "Lo Barnechea", value: "Lo Barnechea" },
  { label: "Lo Espejo", value: "Lo Espejo" },
  { label: "Lo Prado", value: "Lo Prado" },
  { label: "Macul", value: "Macul" },
  { label: "Maipú", value: "Maipú" },
  { label: "Ñuñoa", value: "Ñuñoa" },
  { label: "Pedro Aguirre Cerda", value: "Pedro Aguirre Cerda" },
  { label: "Peñalolén", value: "Peñalolén" },
  { label: "Providencia", value: "Providencia" },
  { label: "Pudahuel", value: "Pudahuel" },
  { label: "Quilicura", value: "Quilicura" },
  { label: "Quinta Normal", value: "Quinta Normal" },
  { label: "Recoleta", value: "Recoleta" },
  { label: "Renca", value: "Renca" },
  { label: "San Miguel", value: "San Miguel" },
  { label: "San Joaquín", value: "San Joaquín" },
  { label: "San Ramón", value: "San Ramón" },
  { label: "Santiago", value: "Santiago" },
  { label: "Vitacura", value: "Vitacura" },
  { label: "El Monte", value: "El Monte" },
  { label: "Isla de Maipo", value: "Isla de Maipo" },
  { label: "Padre Hurtado", value: "Padre Hurtado" },
  { label: "Peñaflor", value: "Peñaflor" },
  { label: "Talagante", value: "Talagante" },
  { label: "Codegua", value: "Codegua" },
  { label: "Coínco", value: "Coínco" },
  { label: "Coltauco", value: "Coltauco" },
  { label: "Doñihue", value: "Doñihue" },
  { label: "Graneros", value: "Graneros" },
  { label: "Las Cabras", value: "Las Cabras" },
  { label: "Machalí", value: "Machalí" },
  { label: "Malloa", value: "Malloa" },
  { label: "Mostazal", value: "Mostazal" },
  { label: "Olivar", value: "Olivar" },
  { label: "Peumo", value: "Peumo" },
  { label: "Pichidegua", value: "Pichidegua" },
  { label: "Quinta de Tilcoco", value: "Quinta de Tilcoco" },
  { label: "Rancagua", value: "Rancagua" },
  { label: "Rengo", value: "Rengo" },
  { label: "Requínoa", value: "Requínoa" },
  {
    label: "San Vicente de Tagua Tagua",
    value: "San Vicente de Tagua Tagua",
  },
  { label: "La Estrella", value: "La Estrella" },
  { label: "Litueche", value: "Litueche" },
  { label: "Marchihue", value: "Marchihue" },
  { label: "Navidad", value: "Navidad" },
  { label: "Paredones", value: "Paredones" },
  { label: "Pichilemu", value: "Pichilemu" },
  { label: "Chépica", value: "Chépica" },
  { label: "Chimbarongo", value: "Chimbarongo" },
  { label: "Lolol", value: "Lolol" },
  { label: "Nancagua", value: "Nancagua" },
  { label: "Palmilla", value: "Palmilla" },
  { label: "Peralillo", value: "Peralillo" },
  { label: "Placilla", value: "Placilla" },
  { label: "Pumanque", value: "Pumanque" },
  { label: "San Fernando", value: "San Fernando" },
  { label: "Santa Cruz", value: "Santa Cruz" },
  { label: "Cauquenes", value: "Cauquenes" },
  { label: "Chanco", value: "Chanco" },
  { label: "Pelluhue", value: "Pelluhue" },
  { label: "Curicó", value: "Curicó" },
  { label: "Hualañé", value: "Hualañé" },
  { label: "Licantén", value: "Licantén" },
  { label: "Molina", value: "Molina" },
  { label: "Rauco", value: "Rauco" },
  { label: "Romeral", value: "Romeral" },
  { label: "Sagrada Familia", value: "Sagrada Familia" },
  { label: "Teno", value: "Teno" },
  { label: "Vichuquén", value: "Vichuquén" },
  { label: "Colbún", value: "Colbún" },
  { label: "Linares", value: "Linares" },
  { label: "Longaví", value: "Longaví" },
  { label: "Parral", value: "Parral" },
  { label: "Retiro", value: "Retiro" },
  { label: "San Javier", value: "San Javier" },
  { label: "Villa Alegre", value: "Villa Alegre" },
  { label: "Yerbas Buenas", value: "Yerbas Buenas" },
  { label: "Constitución", value: "Constitución" },
  { label: "Curepto", value: "Curepto" },
  { label: "Empedrado", value: "Empedrado" },
  { label: "Maule", value: "Maule" },
  { label: "Pelarco", value: "Pelarco" },
  { label: "Pencahue", value: "Pencahue" },
  { label: "Río Claro", value: "Río Claro" },
  { label: "San Clemente", value: "San Clemente" },
  { label: "San Rafael", value: "San Rafael" },
  { label: "Talca", value: "Talca" },
  { label: "Arauco", value: "Arauco" },
  { label: "Cañete", value: "Cañete" },
  { label: "Contulmo", value: "Contulmo" },
  { label: "Curanilahue", value: "Curanilahue" },
  { label: "Lebu", value: "Lebu" },
  { label: "Los Álamos", value: "Los Álamos" },
  { label: "Tirúa", value: "Tirúa" },
  { label: "Alto Biobío", value: "Alto Biobío" },
  { label: "Antuco", value: "Antuco" },
  { label: "Cabrero", value: "Cabrero" },
  { label: "Laja", value: "Laja" },
  { label: "Los Ángeles", value: "Los Ángeles" },
  { label: "Mulchén", value: "Mulchén" },
  { label: "Nacimiento", value: "Nacimiento" },
  { label: "Negrete", value: "Negrete" },
  { label: "Quilaco", value: "Quilaco" },
  { label: "Quilleco", value: "Quilleco" },
  { label: "San Rosendo", value: "San Rosendo" },
  { label: "Santa Bárbara", value: "Santa Bárbara" },
  { label: "Tucapel", value: "Tucapel" },
  { label: "Yumbel", value: "Yumbel" },
  { label: "Chiguayante", value: "Chiguayante" },
  { label: "Concepción", value: "Concepción" },
  { label: "Coronel", value: "Coronel" },
  { label: "Florida", value: "Florida" },
  { label: "Hualpén", value: "Hualpén" },
  { label: "Hualqui", value: "Hualqui" },
  { label: "Lota", value: "Lota" },
  { label: "Penco", value: "Penco" },
  { label: "San Pedro de La Paz", value: "San Pedro de La Paz" },
  { label: "Santa Juana", value: "Santa Juana" },
  { label: "Talcahuano", value: "Talcahuano" },
  { label: "Tomé", value: "Tomé" },
  { label: "Bulnes", value: "Bulnes" },
  { label: "Chillán", value: "Chillán" },
  { label: "Chillán Viejo", value: "Chillán Viejo" },
  { label: "Cobquecura", value: "Cobquecura" },
  { label: "Coelemu", value: "Coelemu" },
  { label: "Coihueco", value: "Coihueco" },
  { label: "El Carmen", value: "El Carmen" },
  { label: "Ninhue", value: "Ninhue" },
  { label: "Ñiquen", value: "Ñiquen" },
  { label: "Pemuco", value: "Pemuco" },
  { label: "Pinto", value: "Pinto" },
  { label: "Portezuelo", value: "Portezuelo" },
  { label: "Quillón", value: "Quillón" },
  { label: "Quirihue", value: "Quirihue" },
  { label: "Ránquil", value: "Ránquil" },
  { label: "San Carlos", value: "San Carlos" },
  { label: "San Fabián", value: "San Fabián" },
  { label: "San Ignacio", value: "San Ignacio" },
  { label: "San Nicolás", value: "San Nicolás" },
  { label: "Treguaco", value: "Treguaco" },
  { label: "Yungay", value: "Yungay" },
  { label: "Carahue", value: "Carahue" },
  { label: "Cholchol", value: "Cholchol" },
  { label: "Cunco", value: "Cunco" },
  { label: "Curarrehue", value: "Curarrehue" },
  { label: "Freire", value: "Freire" },
  { label: "Galvarino", value: "Galvarino" },
  { label: "Gorbea", value: "Gorbea" },
  { label: "Lautaro", value: "Lautaro" },
  { label: "Loncoche", value: "Loncoche" },
  { label: "Melipeuco", value: "Melipeuco" },
  { label: "Nueva Imperial", value: "Nueva Imperial" },
  { label: "Padre Las Casas", value: "Padre Las Casas" },
  { label: "Perquenco", value: "Perquenco" },
  { label: "Pitrufquén", value: "Pitrufquén" },
  { label: "Pucón", value: "Pucón" },
  { label: "Saavedra", value: "Saavedra" },
  { label: "Temuco", value: "Temuco" },
  { label: "Teodoro Schmidt", value: "Teodoro Schmidt" },
  { label: "Toltén", value: "Toltén" },
  { label: "Vilcún", value: "Vilcún" },
  { label: "Villarrica", value: "Villarrica" },
  { label: "Angol", value: "Angol" },
  { label: "Collipulli", value: "Collipulli" },
  { label: "Curacautín", value: "Curacautín" },
  { label: "Ercilla", value: "Ercilla" },
  { label: "Lonquimay", value: "Lonquimay" },
  { label: "Los Sauces", value: "Los Sauces" },
  { label: "Lumaco", value: "Lumaco" },
  { label: "Purén", value: "Purén" },
  { label: "Renaico", value: "Renaico" },
  { label: "Traiguén", value: "Traiguén" },
  { label: "Victoria", value: "Victoria" },
  { label: "Corral", value: "Corral" },
  { label: "Lanco", value: "Lanco" },
  { label: "Los Lagos", value: "Los Lagos" },
  { label: "Máfil", value: "Máfil" },
  { label: "Mariquina", value: "Mariquina" },
  { label: "Paillaco", value: "Paillaco" },
  { label: "Panguipulli", value: "Panguipulli" },
  { label: "Valdivia", value: "Valdivia" },
  { label: "Futrono", value: "Futrono" },
  { label: "La Unión", value: "La Unión" },
  { label: "Lago Ranco", value: "Lago Ranco" },
  { label: "Río Bueno", value: "Río Bueno" },
  { label: "Ancud", value: "Ancud" },
  { label: "Castro", value: "Castro" },
  { label: "Chonchi", value: "Chonchi" },
  { label: "Curaco de Vélez", value: "Curaco de Vélez" },
  { label: "Dalcahue", value: "Dalcahue" },
  { label: "Puqueldón", value: "Puqueldón" },
  { label: "Queilén", value: "Queilén" },
  { label: "Quemchi", value: "Quemchi" },
  { label: "Quellón", value: "Quellón" },
  { label: "Quinchao", value: "Quinchao" },
  { label: "Calbuco", value: "Calbuco" },
  { label: "Cochamó", value: "Cochamó" },
  { label: "Fresia", value: "Fresia" },
  { label: "Frutillar", value: "Frutillar" },
  { label: "Llanquihue", value: "Llanquihue" },
  { label: "Los Muermos", value: "Los Muermos" },
  { label: "Maullín", value: "Maullín" },
  { label: "Puerto Montt", value: "Puerto Montt" },
  { label: "Puerto Varas", value: "Puerto Varas" },
  { label: "Osorno", value: "Osorno" },
  { label: "Puerto Octay", value: "Puerto Octay" },
  { label: "Purranque", value: "Purranque" },
  { label: "Puyehue", value: "Puyehue" },
  { label: "Río Negro", value: "Río Negro" },
  { label: "San Juan de la Costa", value: "San Juan de la Costa" },
  { label: "San Pablo", value: "San Pablo" },
  { label: "Chaitén", value: "Chaitén" },
  { label: "Futaleufú", value: "Futaleufú" },
  { label: "Hualaihué", value: "Hualaihué" },
  { label: "Palena", value: "Palena" },
  { label: "Aisén", value: "Aisén" },
  { label: "Cisnes", value: "Cisnes" },
  { label: "Guaitecas", value: "Guaitecas" },
  { label: "Cochrane", value: "Cochrane" },
  { label: "O'higgins", value: "O'higgins" },
  { label: "Tortel", value: "Tortel" },
  { label: "Coihaique", value: "Coihaique" },
  { label: "Lago Verde", value: "Lago Verde" },
  { label: "Chile Chico", value: "Chile Chico" },
  { label: "Río Ibáñez", value: "Río Ibáñez" },
  { label: "Antártica", value: "Antártica" },
  { label: "Cabo de Hornos", value: "Cabo de Hornos" },
  { label: "Laguna Blanca", value: "Laguna Blanca" },
  { label: "Punta Arenas", value: "Punta Arenas" },
  { label: "Río Verde", value: "Río Verde" },
  { label: "San Gregorio", value: "San Gregorio" },
  { label: "Porvenir", value: "Porvenir" },
  { label: "Primavera", value: "Primavera" },
  { label: "Timaukel", value: "Timaukel" },
  { label: "Natales", value: "Natales" },
  { label: "Torres del Paine", value: "Torres del Paine" },
  { label: "Cabildo", value: "Cabildo" },
];

export { comunas };
