import { formateDate } from "../functions/formateDate";

const showErrorTextarea = window.location.search.split("=")[1];

const schema = [
  // {
  //   $formkit: "date",
  //   name: "date",
  //   label: "Fecha supervisión",
  //   help: "Fecha en que se visitó a trabajador/a",
  //   "label-class": "!text-[#003D80]",
  //   classes: {
  //     help: "textoAzul",
  //   },
  //   validation: "required|date_after:2023-01-01",
  // },
  {
    $formkit: "datetime-local",
    name: "datetime",
    label: "Fecha y hora de supervisión",
    help: "Fecha y hora en que se visitó a trabajador/a",
    value: formateDate(new Date().toISOString()),
    "label-class": "!text-[#003D80]",
    "help-class": "!text-[#003D80]",
    validation: "required|date_after:2023-01-01",
  },
  // {
  //   $formkit: "time",
  //   name: "time",
  //   label: "Hora supervisión",
  //   help: "Hora en que se visitó a trabajador/a",
  //   "label-class": "!text-[#003D80]",
  //   classes: {
  //     help: "textoAzul",
  //   },
  //   validation: "required|time",
  // },
  // {
  //   $formkit: "select",
  //   autocomplete: true,
  //   name: "comuna",
  //   id: "comuna",
  //   label: "Comuna en que trabaja",
  //   placeholder: "Escribe la comuna",
  //   options: comunas,
  //   "label-class": "!text-[#003D80]",

  // },
  {
    $formkit: "toggle",
    name: "presencia",
    id: "presencia",
    label: "Se encontraba en el lugar",
    "label-class": "!text-[#003D80]",
    "help-class": "!text-[#003D80]",
  },
  {
    $formkit: "toggle",
    name: "firma",
    id: "firma",
    label: "Firma libro de asistencia",
    "label-class": "!text-[#003D80]",
    "help-class": "!text-[#003D80]",
  },
  {
    $formkit: "toggle",
    name: "horarios_firma",
    id: "horarios_firma",
    label: "Cumple horarios según libro",
    "label-class": "!text-[#003D80]",
    "help-class": "!text-[#003D80]",
  },
  {
    $formkit: "toggle",
    name: "funcion_contrato",
    id: "funcion_contrato",
    label: "Cumple funciones según contrato",
    "label-class": "!text-[#003D80]",
    "help-class": "!text-[#003D80]",
  },
  // {
  //   $formkit: "textarea",
  //   if: "$get(funcion_contrato).value",
  //   name: "comentario_funcion_contrato",
  //   label: "¿Qué función está realizando la trabajadora?",
  //   "label-class": "!text-[#003D80]",
  // },
  {
    $formkit: "toggle",
    name: "utiliza_epp",
    id: "utiliza_epp",
    label: "Utiliza EPP",
    "label-class": "!text-[#003D80]",
    "help-class": "!text-[#003D80]",
  },
  {
    $formkit: "textarea",
    // if: "$get(utiliza_epp).value",
    name: "comentario_utiliza_epp",
    label: "Comentarios respecto a los EPP (opcional)",
    placeholder:
      "Mencionar motivos por el cual beneficiaria/o no utiliza elementos de protección personal.",
    "label-class": "!text-[#003D80]",
    "help-class": "!text-[#003D80]",
  },
  {
    $formkit: "toggle",
    name: "herramientas",
    id: "herramientas",
    label: "Cuenta con insumos adecuados",

    "label-class": "!text-[#003D80]",
    "help-class": "!text-[#003D80]",
  },
  {
    $formkit: "textarea",
    // if: "$get(herramientas).value",
    name: "comentario_herramientas",
    label: "Comentario respecto a insumos (opcional)",
    placeholder:
      "Mencionar motivos por el cual beneficiaria/o no ha recibido insumos.",
    "label-class": "!text-[#003D80]",
    "help-class": "!text-[#003D80]",
  },
  {
    $formkit: "toggle",
    name: "condiciones_espacio_laboral",
    id: "condiciones_espacio_laboral",
    label: "Condiciones laborales adecuadas",
    "label-class": "!text-[#003D80]",
    "help-class": "!text-[#003D80]",
  },
  // {
  //   $formkit: "textarea",
  //   if: "$get(condiciones_espacio_laboral).value",
  //   name: "comentario_condiciones_espacio_laboral",
  //   label: "Describe falencias espacio laboral",
  //   "label-class": "!text-[#003D80]",
  // "help-class": "!text-[#003D80]",
  // },
  // {
  //   $formkit: "toggle",
  //   name: "condiciones_maquinas",
  //   id: "condiciones_maquinas",
  //   label: "Herramientas en buen estado",
  //   "label-class": "!text-[#003D80]",
  // "help-class": "!text-[#003D80]",
  // },
  // {
  //   $formkit: "textarea",
  //   if: "$get(condiciones_maquinas).value",
  //   name: "comentario_condiciones_maquinas",
  //   label: "Describe condiciones de máquinas o insumos",
  //   "label-class": "!text-[#003D80]",
  // "help-class": "!text-[#003D80]",
  // },
  {
    $formkit: "toggle",
    name: "logo_proempleo",
    id: "logo_proempleo",
    label: "Indumentaria cuenta con logo ProEmpleo",
    "label-class": "!text-[#003D80]",
    "help-class": "!text-[#003D80]",
  },
  {
    $formkit: "toggle",
    name: "fiscalizacion_ejecutora",
    id: "fiscalizacion_ejecutora",
    label: "¿Ejecutora ha supervisado?",
    "label-class": "!text-[#003D80]",
    "help-class": "!text-[#003D80]",
  },
  {
    $formkit: "date",
    name: "supervision_ejecutora",
    if: "$get(fiscalizacion_ejecutora).value",
    label: "Fecha última supervisión ejecutora",
    help: "Fecha en que ejecutora visitó a trabajador/a",
    "label-class": "!text-[#003D80]",
    "help-class": "!text-[#003D80]",
  },
  {
    $formkit: "textarea",
    name: "observaciones",
    label: "Observaciones de fiscalización en terreno",
    "label-class": "!text-[#003D80]",
    "help-class": "!text-[#003D80]",
    placeholder: "Observaciones generales de supervisión.",
  },
  {
    $formkit: "textarea",
    // if: `false`,
    if: `${showErrorTextarea}`,
    name: "errorDatos",
    label: "Reportar errores en datos personales",
    "label-class": "!text-[#003D80]",
    "help-class": "!text-[#003D80]",
    placeholder: "En caso de exitir.",
  },
  {
    $formkit: "file",
    name: "file",
    label: "Cargar archivos",
    "label-class": "!text-[#003D80]",
    "help-class": "!text-[#003D80]",
    "noFilesIcon-class": "!text-[#003D80]",
    "noFiles-class": "!text-[#003D80]",
    "fileName-class": "!text-[#003D80]",
    accept: ".jpg, .jpeg, .png, .gif, .heif, .hevc, .docx, .xlsx",
    multiple: "false",
    // validation: "required|file",
  },
];

export { schema };
